parameters:
#    juego.example.class: CloudFutbol\JuegoBundle\Example

services:
#    juego.example:
#        class: %juego.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
